package com.yuaicodeuser;

import org.apache.dubbo.config.spring.context.annotation.EnableDubbo;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication//不需要使用redis的向量存储功能。
@MapperScan("com.yuaicodeuser.mapper")
@EnableDubbo
public class YuAiCodeUserApplication {

    public static void main(String[] args) {
        SpringApplication.run(YuAiCodeUserApplication.class, args);
    }

}
