package com.yuaicodemother;

import dev.langchain4j.community.store.embedding.redis.spring.RedisEmbeddingStoreAutoConfiguration;
import org.apache.dubbo.config.spring.context.annotation.EnableDubbo;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cache.annotation.EnableCaching;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication(exclude = {RedisEmbeddingStoreAutoConfiguration.class})//不需要使用redis的向量存储功能。
@MapperScan("com.yuaicodemother.mapper")
@EnableCaching//启用springdata缓存注解功能
@EnableDubbo
public class YuAiCodeMotherAppApplication {

    public static void main(String[] args) {
        SpringApplication.run(YuAiCodeMotherAppApplication.class, args);
    }

}
